version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./dist/:/usr/share/nginx/html/
    restart: unless-stopped
    networks:
      nw:
        aliases:
          - web

  postgres:
    image: postgres
    volumes:
    - dbs/var/lib/postgresql/data
    ports:
      - '27017:27017'
    restart: unless-stopped
    networks:
      nw:
        aliases:
          - postgres
networks:
  nw:
